---
abstract: 'Control the WumpusRover'
author:
  - 'Timm Murray <tmurray@wumpus-cave.net>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140630'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: UAV-Pilot-WumpusRover-Server
provides:
  UAV::Pilot::WumpusRover::Server:
    file: lib/UAV/Pilot/WumpusRover/Server.pm
    version: '0.2'
  UAV::Pilot::WumpusRover::Server::Backend:
    file: lib/UAV/Pilot/WumpusRover/Server/Backend.pm
  UAV::Pilot::WumpusRover::Server::Backend::Mock:
    file: lib/UAV/Pilot/WumpusRover/Server/Backend/Mock.pm
  UAV::Pilot::WumpusRover::Server::Backend::RaspberryPiI2C:
    file: lib/UAV/Pilot/WumpusRover/Server/Backend/RaspberryPiI2C.pm
  UAV::Pilot::WumpusRover::Server::Mock:
    file: lib/UAV/Pilot/WumpusRover/Server/Mock.pm
recommends:
  Getopt::Long: '0'
requires:
  AnyEvent: '0'
  HiPi: '0'
  Moose: '0'
  Test::More: '0'
  Throwable: '0'
  Tie::IxHash: '0'
  UAV::Pilot: '0.8'
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/frezik/UAV-Pilot-WumpusRover-Server
version: '0.2'
